export const Config = {
	API_BASE_PATH : 'http://34.237.70.31/medirecx-dev-api/api/v1/',
	//API_BASE_PATH : 'http://localhost:1337/api/v1/',
	APP_TITLE : 'MediRecX',
	TIMEOUT_SECONDS: 3000000000000,
	API_SUPERADMIN_KEY : "bXktZW4tcHJvLWRldmVsb3BtZW50LXNlY3JldC1rZXlAMjAxOSE=",
	//API_CLINIC_KEY : "bXktZW4tcHJvLWRldmVsb3BtZW50LXNlY3JldC1rZXlAMjAxOSE=",
	API_OTHERS_KEY : "aHC$kykHa=aZHC#yZZkA$#HyHaCkH=k#akHkkZ$C$ZaAakHZ",
	BAD_REQUEST_STATUS : 400 ,
	SUCCESS_STATUS : 200 ,
	REGISTRATION_TITLE: "Registration",
	SUPPORT_EMAIL: "support@medirecx.com",
	SUPPORT_PHONE: "+1 408 655 7179",
	COMMON_ERROR : 'Something went wrong, please try again later.',
	FORGOT_PASSWORD_TITLE: "Forgot Password",
	RESET_PASSWORD_TITLE: "Reset Password",
	CHANGE_PASSWORD_TITLE: "Change Password",
	NOT_FOUND_TITLE: "404 Not Found",
	SUPERADMIN_TITLE: "Super Admin",
	CLINIC_TITLE: "Clinic Title",
	TITLE_SEPRATOR: " :: ",
	LOGIN_TITLE: "Login",
	BAD_AUTH_STATUS: 401,
	USERNAME_REQUIRED_VALIDATION_MSG: "Username is required.",
	EMAIL_REQUIRED_VALIDATION_MSG: "Email is required.",
	EMAIL_FORMAT_VALIDATION_MSG: "Email address is not vaild.",
	PASSWORD_REQUIRED_VALIDATION_MSG: "Password is required.",
	PASSWORD_NOT_VALID_VALIDATION_MSG: "Password should be minimum 8 characters & maximum 16 characters long, alphanumeric, with 1 special character.",
	PASSWORD_MISMATCH_VALIDATION_MSG: "Password and Confirm Password are not same.",
	CONFIRM_PASSWORD_REQUIRED_VALIDATION_MSG: "Confirm Password is required.",
	RESET_PASSWORD_SUCCESS_MSG: "Password has been reset/changed successfully.",
	PAGE_RELOAD_TIMEOUT_SECONDS:500,
	SPINNER_TIMEOUT_SECONDS: 100,
	BLOCK_UI_TIMEOUT_SECONDS: 2000,
	BLOCK_UI_UPDATE_TIMEOUT_SECONDS:850,
	AUTHORIZATION_NOT_VALID_STATUS:501,
	ALERT_AUTO_REMOVE_TIME:2000,
	DEFAULT_PAGE_SIZE:10,
	FORGOT_PASSWORD_SUCCESS_MSG: "Please check your email as we have sent you a link to reset your password.",
	PASSWORD_REGX: "(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*]).{8,16}",
	SIDEBAR_LOGO_PATH: "assets/img/favicon.png",
	PROFILE_NO_IMG_PATH: "assets/img/profile-no-img.jpg",
	UNDER_CONSTRUCTION_IMG_PATH: "assets/img/under-construction-img.jpg",	
	CLINIC_UNDER_CONSTRUCTION_IMG_PATH: "assets/img/clinic_uc.png",
	CLINIC_LOGO_DEFAULT_IMG_PATH: "assets/img/clinic.png",
	OLD_PASSWORD_REQUIRED_VALIDATION_MSG: "Old Password is required.",
	NEW_PASSWORD_REQUIRED_VALIDATION_MSG: "New Password is required.",
	NEW_PASSWORD_NOT_VALID_VALIDATION_MSG: "New Password should be minimum 8 characters & maximum 16 characters long, alphanumeric, with 1 special character.",
	NEW_PASSWORD_MISMATCH_VALIDATION_MSG: "New Password and Confirm Password are not same.",
	SWAL_LOGOUT_TITLE: "Ready to Leave?",
	SWAL_LOGOUT_TEXT: "Select \"Logout\" below if you are ready to end your current session.",
	SWAL_LOGOUT_CONFIRM_BUTTON_TEXT: "Logout",
	PLEASE_FILL_REQUIRED_FIELD_MSG : "Please fill the required fields.",
	UNAME_PATTERN: "^[a-z0-9_-]{8,16}$",
	UNAME_NOT_VALID_MESSAGE: "Username should be minimum 8 characters & maximum 16 characters long with alphanumeric.",
	KEYWORD_PATTERN: "^[a-z0-9]{3,16}$",
	KEYWORD_NOT_VALID_MESSAGE: "Keyword should be minimum 3 characters & maximum 16 characters long with small characters and number only.",
	CLNAME_PATTERN: "^[a-zA-Z0-9_ -]{4,20}$",
	CLNAME_NOT_VALID_MESSAGE: "Clinic name should be minimum 4 characters & maximum 20 characters long with alphanumeric.",
	NAME_PATTERN: "^(?=.{3,16}$)[a-zA-Z]+(?:[-'\s][a-zA-Z]+)*$",
	NAME_NOT_VALID_MESSAGE: "Name should be minimum 3 characters & maximum 16 characters long with alphabate.",
	PHONE_PATTERN: "^((\\+91-?)|0)?[0-9]{10}$",
	ZIP_PATTERN: "^[0-9]{6}",
	PHONE_NOT_VALID_MESSAGE: "Phone number should of 10 character numeric only.",
	ZIP_NOT_VALID_MESSAGE: "Zip code should of 6 character numeric only.",
	EMAIL_PATTERN: "^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$",
	EMAIL_NOT_VALID_MESSAGE: "Please enter valid email format.",
	STATUS_UPDATED_SUCCESSFULLY: "Status updated successfully.",	
	DOCUMENT_ADDED_SUCCESSFULLY: "Document added successfully.",
	DOCUMENT_UPDATED_SUCCESSFULLY: "Document updated successfully.",
	DOCUMENT_DELETED_SUCCESSFULLY: "Document deleted successfully.",	
	ROLE_ADDED_SUCCESSFULLY: "Role added successfully.",
	ROLE_UPDATED_SUCCESSFULLY: "Role updated successfully.",
	ROLE_DELETED_SUCCESSFULLY: "Role deleted successfully.",
	CLAIM_ADDED_SUCCESSFULLY: "Claim added successfully.",
	CLAIM_UPDATED_SUCCESSFULLY: "Claim updated successfully.",
	CLAIM_DELETED_SUCCESSFULLY: "Status updated successfully.",
	PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
	CLINIC_ACCUOUNT_EXPIRED: "Account expired. Please contact to administrator.",
	PROFILE_IMG_S3_PATH: "https://medirecx.s3.amazonaws.com/user-avtar/",
	DOC_IMG_S3_PATH: "https://medirecx.s3.amazonaws.com/document/",
	MESSAGE_SEND_SUCCESSFULLY: "Message sent successfully.",
	SUBDOMAIN: "",
	STATUS:"<html><body><ul><li>Uploaded</li><li> Sent to Medpro</li><li>Sent to Doctor</li><li>Reviewed by Medpro</li><li>Reviewed by Doctor</li><li>Doctor sent to medpro</li><li>Medpro sent to clinic</li><li>Completed</li><li>Inactive</li></ul></body></html>"
	
}



